version: "3.9"
volumes:
  postgres-data:

services:
  db:
    image: "postgres"
    env_file:
      - .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./migrate/stopify.sql:/docker-entrypoint-initdb.d/dumpfile.sql
  server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: >
      sh -c "npx prisma migrate dev &&
            npx prisma generate dev &&
            npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
